Add an update command
- update command must currently delete function resources in order to get any modified function resources to take effect

diff --git a/riff b/riff
--- a/riff
+++ b/riff
@@ -14,6 +14,7 @@ Commands:
   build        Build a function container
   apply        Apply function resource definitions
   create       Create function resources, build container and apply the function resources
+  update       Build the container and apply the modified function resources
   delete       Delete function resource definitions
   list         List current function resources
   logs         Show logs for a function resource
@@ -125,6 +126,25 @@ Usage:
 Options:
 
   -f, --filename: filename, directory, or URL for the resource definition[s] (defaults to the current directory)
+
+EOF
+}
+
+function print_update_usage() {
+cat <<EOF
+
+Build the container image and apply the modified function resource definition[s] that the path points to.
+
+Usage:
+
+  riff update -n <name> -v <version> -f <path> [--push]
+
+Options:
+
+  -n, --name: the name of the function (defaults to the name of the current directory)
+  -v, --version: the version of the function (defaults to 0.0.1)
+  -f, --filename: filename, directory, or URL for the code or resource (defaults to the current directory)
+  --push: push the image to Docker registry
 
 EOF
 }
@@ -429,6 +449,22 @@ function create() {
   apply
 }
 
+function update() {
+  if [ -f "${FNPATH}" ] ; then
+    FNPATH=$(dirname "$FNPATH")
+  fi
+  FNDOCKER="$FNPATH/Dockerfile"
+  if [ -f $FNDOCKER ] ; then
+    echo "Updating $FNPATH resource[s]"
+    kubectl delete -f $FNPATH
+    build
+    apply
+  else
+    echo "Resource files not found in $FNPATH directory, not able to update function $FUNCTION"
+    exit 1
+  fi
+}
+
 function delete() {
   echo "Deleting $FUNCTION resource[s]"
   if [[ $DELETEALL == "true" ]] ; then
@@ -479,6 +515,9 @@ if [[ $1 == "--help" || $1 == "-h" ]] ; then
     exit 0
   elif [[ "${COMMAND}" == "apply" ]]; then
     print_apply_usage
+    exit 0
+  elif [[ "${COMMAND}" == "update" ]]; then
+    print_update_usage
     exit 0
   elif [[ "${COMMAND}" == "delete" ]]; then
     print_delete_usage
@@ -586,6 +625,8 @@ elif [[ "${COMMAND}" == "create" ]]; then
   create
 elif [[ "${COMMAND}" == "apply" ]]; then
   apply
+elif [[ "${COMMAND}" == "update" ]]; then
+  update
 elif [[ "${COMMAND}" == "delete" ]]; then
   delete
 elif [[ "${COMMAND}" == "list" ]]; then
