Add publish command
- use `-t` to "tail" waiting for the response -- `riff publish -d "world" -t`

- use `--count` to publish multiple messages (use ${i} variable to get the iteration) -- `riff publish -d 'My test ${i}' --count 3`

diff --git a/riff b/riff
--- a/riff
+++ b/riff
@@ -18,6 +18,7 @@ Commands:
   delete       Delete function resource definitions
   list         List current function resources
   logs         Show logs for a function resource
+  publish      Publish data to a topic using the http-gateway
   version      Display the riff version
 
   Use "riff <command> --help" for more information about a given command.
@@ -195,6 +196,26 @@ Options:
   -n, --name: the name of the function (defaults to the name of the current directory)
   -c, --container: the name of the container, usually sidecar or main (defaults to sidecar)
   -t, --tail: tail the logs
+
+EOF
+}
+
+function print_publish_usage() {
+cat <<EOF
+
+Publish data to a topic using the http-gateway.
+
+Usage:
+
+  riff publish -i <input-topic> -d <data> [--count <count>] [--pause <pause>] [-t]
+
+Options:
+
+  -i, --input: the name of the input topic (defaults to the name of the current directory)
+  -d, --data: the data to post to the http-gatewy using the input topic
+  --count: the number of times to post the data (defaults to 1)
+  --pause: the number of seconds to wait bewteen postings (defaults to 0)
+  -t, --tail: tail, waiting for the function response
 
 EOF
 }
@@ -484,6 +505,46 @@ function logs() {
   kubectl logs ${TAIL} -c ${CONTAINER} $(kubectl get pod -l function=${FUNCTION} -o jsonpath='{.items[0].metadata.name}')
 }
 
+function publish() {
+  svc=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items}')
+  if [[ $svc == "[]" ]] ; then
+    echo "Unable to locate the http-gateway"
+    exit 1
+  fi
+
+  type=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items[0].spec.type}')
+  if [[ $type == "NodePort" ]] ; then
+    address=$(minikube ip 2>/dev/null)
+    if [[ "$address" == "" ]] ; then
+      address=127.0.0.1
+    fi
+    port=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items[0].spec.ports[?(@.name == "http")].nodePort}')
+  else
+    address=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}')
+    if [[ $address == "" ]] ; then
+      echo "External IP is not yet available, try in a few ..."
+      exit 1
+    fi
+    port=$(kubectl get svc -l component=http-gateway -o jsonpath='{.items[0].spec.ports[?(@.name == "http")].port}')
+  fi
+
+  count=${PUB_COUNT:-1}
+  pause=${PUB_PAUSE:-0}
+
+  if [ -z $TOPIC_IN ] ; then
+    TOPIC_IN="${FUNCTION:-${PWD##*/}}"
+  fi
+
+  for ((i=1; i<=$count; i++)); do
+    if [[ $TAIL == "-f" ]] ; then
+      curl -w "\n" -H "Content-Type: text/plain" http://$address:$port/requests/$TOPIC_IN -d $(eval echo "$PUB_DATA")
+    else
+      curl -H "Content-Type: text/plain" http://$address:$port/messages/$TOPIC_IN -d $(eval echo "$PUB_DATA")
+    fi
+    sleep $pause
+  done
+}
+
 function version() {
   echo "riff version $RIFF_VERSION"
 }
@@ -527,6 +588,9 @@ if [[ $1 == "--help" || $1 == "-h" ]] ; then
     exit 0
   elif [[ "${COMMAND}" == "logs" ]]; then
     print_logs_usage
+    exit 0
+  elif [[ "${COMMAND}" == "publish" ]]; then
+    print_publish_usage
     exit 0
   elif [[ "${COMMAND}" == "version" ]]; then
     print_version_usage
@@ -585,6 +649,18 @@ case ${key} in
   TOPIC_OUT="$2"
   shift
   ;;
+  -d|--data)
+  PUB_DATA="$2"
+  shift
+  ;;
+  --count)
+  PUB_COUNT="$2"
+  shift
+  ;;
+  --pause)
+  PUB_PAUSE="$2"
+  shift
+  ;;
   --riff-version)
   RIFF_VERSION="$2"
   shift
@@ -637,6 +713,8 @@ elif [[ "${COMMAND}" == "list" ]]; then
   list
 elif [[ "${COMMAND}" == "logs" ]]; then
   logs
+elif [[ "${COMMAND}" == "publish" ]]; then
+  publish
 elif [[ "${COMMAND}" == "version" ]]; then
   version
 else
